sudo: required
services:
    - docker
before_install:
    # Encrypted login for travis to Google Cloud
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    # This covers the following steps:
    # 1. Install Google Cloud SDK CLI
    # 2. Configure the SDK without Google Cloud auth info
    # 3. Login to Docker CLI
    # 4. Build the 'test' version of multi-client
    # --------------------------------------------------------
    # Step 1:
    # Install Google Cloud SDK:
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    # Configure the environment:
    - source $HOME/google-cloud-sdk/path.bash.inc
    # Ensure that the kubectl command is installed as well:
    - gcloud components update kubectl
    # Get access via a service account. The credentials are in the json file
    - gcloud auth activate-service-account --key-file service-account.json
